name: Publish Images to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout spotify-api
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u mattmajestic --password-stdin
        env:
          DOCKER_BUILDKIT: 1  # Set this environment variable for buildx

      - name: Spotify API ~ Build and Push 
        run: |
          docker buildx create --use
          docker buildx build -t mattmajestic/spotify-api:latest -f Dockerfile . --push
